In [35]:
import tensorflow as tf
import numpy as np

In [36]:
a = tf.constant(3.0)
b = tf.constant(4.0)
c = tf.sqrt(a**2 + b**2)

print('c:', c)
print(f'c: {c}')
print('c in numpy:', c.numpy())

c: tf.Tensor(5.0, shape=(), dtype=float32)
c: 5.0
c in numpy: 5.0


In [37]:
# vector multiplication
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])
c = tf.tensordot(a, b, axes=[0,0])

print('c:', c)
print(f'c: {c}')
print('c in numpy:', a.numpy().dot(b.numpy()))

c: tf.Tensor(32, shape=(), dtype=int32)
c: 32
c in numpy: 32


In [38]:
# matrix multiplication
A0 = np.random.randn(3,3)
b0 = np.random.randn(3,1)
A = tf.constant(A0)
b = tf.constant(b0)
c = tf.matmul(A, b)

print('c:', c)
print(f'c: {c}')
print('c:', c.numpy())
print('c in numpy:', A0.dot(b0))

c: tf.Tensor(
[[-0.76564206]
 [ 0.64051768]
 [ 1.79528951]], shape=(3, 1), dtype=float64)
c: [[-0.76564206]
 [ 0.64051768]
 [ 1.79528951]]
c: [[-0.76564206]
 [ 0.64051768]
 [ 1.79528951]]
c in numpy: [[-0.76564206]
 [ 0.64051768]
 [ 1.79528951]]


In [39]:
# broadcasting
a = tf.constant([[1,2],[3,4]])
b = tf.constant(1)
c = a + b

print('c:', c)
print(f'c: {c}')
print('c in numpy:', a.numpy() + b.numpy())

c: tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
c: [[2 3]
 [4 5]]
c in numpy: [[2 3]
 [4 5]]


In [41]:
# elementwise multiplication
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[2,3],[4,5]])
c = a * b

print('c:', c)
print(f'c: {c}')
print('c in numpy:', a.numpy() * b.numpy())

c: tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)
c: [[ 2  6]
 [12 20]]
c in numpy: [[ 2  6]
 [12 20]]
